import TrackStayContactAllTime
import TrackThetaAllTime

/-!
# Explicit action corners for every manufactured reflector pair

The flat four-vector theorem is strengthened pointwise: at every time the
pair trajectory lies in the four algebraic corners generated by the two local
actions.  Stay actions collapse corners, intersecting stay/flip pairs use the
existing two-phase laws, and flip/flip pairs use the absolute theta theorem.
-/

namespace GeneralN

/-- The four algebraic action corners of an opposite manufactured pair. -/
def manufacturedPairActionCorners
    {w : Wiring} {g e : Nat}
    (A : ManufacturedReflector w g e)
    (B : ManufacturedReflector w e g)
    (state : Tongues) : List Tongues :=
  [state,
   A.toSupported.action.apply state,
   B.toSupported.action.apply state,
   B.toSupported.action.apply (A.toSupported.action.apply state)]

/-- **Pointwise action-corner law for every opposite manufactured pair.** -/
theorem manufactured_pair_all_time_action_corners_tongues
    {w : Wiring} {g e : Nat}
    (A : ManufacturedReflector w g e)
    (B : ManufacturedReflector w e g)
    (state : Tongues)
    (hA : PathGrooves A.toSupported.paths state)
    (hB : PathGrooves B.toSupported.paths state)
    (d : Nat) :
    tonguesAt w (g, state) d ∈
      manufacturedPairActionCorners A B state := by
  by_cases hcompatible : A.toSupported.action.Avoids B.toSupported.paths ∧
      B.toSupported.action.Avoids A.toSupported.paths
  · obtain ⟨port, phase, hr, hs⟩ := A.pair_all_time_four_phase B state hA hB
      hcompatible.1 hcompatible.2 d
    simpa [tonguesAt, hr, manufacturedPairActionCorners,
      A.toSupported.action.commute B.toSupported.action] using hs
  · cases A with
    | stay SA =>
        cases B with
        | stay SB => exact (hcompatible ⟨by trivial, by trivial⟩).elim
        | flip FB =>
            have hcontact := contact_of_not_avoids_flip
              (fun h => hcompatible ⟨by trivial, h⟩)
            obtain ⟨port, phase, hr, hp⟩ :=
              manufactured_stay_then_flip_contact_all_time_two_phase SA FB state hA hB hcontact d
            have ht : tonguesAt w (g, state) d = phase := by simp [tonguesAt, hr]
            rw [ht]
            rcases hp with rfl | rfl <;>
              simp [manufacturedPairActionCorners, ManufacturedReflector.toSupported,
                ManufacturedStayReflector.toSupported, ManufacturedFlipReflector.toSupported,
                LocalAction.apply]
    | flip FA =>
        cases B with
        | stay SB =>
            have hcontact := contact_of_not_avoids_flip
              (fun h => hcompatible ⟨h, by trivial⟩)
            obtain ⟨port, phase, hr, hp⟩ :=
              manufactured_flip_then_stay_all_time_two_phase FA SB state hA hB hcontact d
            have ht : tonguesAt w (g, state) d = phase := by simp [tonguesAt, hr]
            rw [ht]
            rcases hp with rfl | rfl <;>
              simp [manufacturedPairActionCorners, ManufacturedReflector.toSupported,
                ManufacturedStayReflector.toSupported, ManufacturedFlipReflector.toSupported,
                LocalAction.apply]
        | flip FB =>
            obtain ⟨port, phase, hr, hm⟩ :=
              manufactured_flip_pair_all_time_four_phase FA FB state hA hB d
            simpa [tonguesAt, hr, manufacturedPairActionCorners,
              ManufacturedReflector.toSupported, ManufacturedFlipReflector.toSupported,
              LocalAction.apply] using hm

end GeneralN
