import TrackStayContactAllTime
import TrackThetaAllTime

/-!
# Explicit action corners for every manufactured reflector pair

The flat four-vector theorem is strengthened pointwise: at every time the
pair trajectory lies in the four algebraic corners generated by the two local
actions.  Stay actions collapse corners, intersecting stay/flip pairs use the
existing two-phase laws, and flip/flip pairs use the absolute theta theorem.
-/

namespace GeneralN

/-- The four algebraic action corners of an opposite manufactured pair. -/
def manufacturedPairActionCorners
    {w : Wiring} {g e : Nat}
    (A : ManufacturedReflector w g e)
    (B : ManufacturedReflector w e g)
    (state : Tongues) : List Tongues :=
  [state,
   A.toSupported.action.apply state,
   B.toSupported.action.apply state,
   B.toSupported.action.apply (A.toSupported.action.apply state)]

/-- **Pointwise action-corner law for every opposite manufactured pair.** -/
theorem manufactured_pair_all_time_action_corners_tongues
    {w : Wiring} {g e : Nat}
    (A : ManufacturedReflector w g e)
    (B : ManufacturedReflector w e g)
    (state : Tongues)
    (hA : PathGrooves A.toSupported.paths state)
    (hB : PathGrooves B.toSupported.paths state)
    (d : Nat) :
    tonguesAt w (g, state) d ∈
      manufacturedPairActionCorners A B state := by
  classical
  cases A with
  | stay SA =>
      cases B with
      | stay SB =>
          have hmem := manufactured_pair_all_time_four_phase_tongues
            (.stay SA) (.stay SB) state hA hB
              (by trivial) (by trivial) d
          simpa [manufacturedPairActionCorners,
            ManufacturedReflector.toSupported,
            ManufacturedStayReflector.toSupported,
            LocalAction.apply] using hmem
      | flip FB =>
          change PathGrooves
            [SA.runway, [(SA.mouth, SA.arm)]] state at hA
          change PathGrooves [FB.runway, FB.candy] state at hB
          by_cases hBA : (LocalAction.flip FB.actionSwitch).Avoids
              [SA.runway, [(SA.mouth, SA.arm)]]
          · have hmem := manufactured_pair_all_time_four_phase_tongues
              (.stay SA) (.flip FB) state hA hB
                (by trivial) hBA d
            simpa [manufacturedPairActionCorners,
              ManufacturedReflector.toSupported,
              ManufacturedStayReflector.toSupported,
              ManufacturedFlipReflector.toSupported,
              LocalAction.apply] using hmem
          · have hcontact := contact_of_not_avoids_flip hBA
            obtain ⟨port, phase, hrun, hphase⟩ :=
              manufactured_stay_then_flip_contact_all_time_two_phase
                SA FB state hA hB hcontact d
            have ht : tonguesAt w (g, state) d = phase := by
              simp [tonguesAt, hrun]
            rw [ht]
            rcases hphase with rfl | rfl <;>
              simp [manufacturedPairActionCorners,
                ManufacturedReflector.toSupported,
                ManufacturedStayReflector.toSupported,
                ManufacturedFlipReflector.toSupported,
                LocalAction.apply]
  | flip FA =>
      cases B with
      | stay SB =>
          change PathGrooves [FA.runway, FA.candy] state at hA
          change PathGrooves
            [SB.runway, [(SB.mouth, SB.arm)]] state at hB
          by_cases hAB : (LocalAction.flip FA.actionSwitch).Avoids
              [SB.runway, [(SB.mouth, SB.arm)]]
          · have hmem := manufactured_pair_all_time_four_phase_tongues
              (.flip FA) (.stay SB) state hA hB
                hAB (by trivial) d
            have hmem' :
                tonguesAt w (g, state) d = state ∨
                  tonguesAt w (g, state) d =
                    flipAt state FA.actionSwitch ∨
                  tonguesAt w (g, state) d = state := by
              simpa [ManufacturedReflector.toSupported,
                ManufacturedStayReflector.toSupported,
                ManufacturedFlipReflector.toSupported,
                LocalAction.apply, flipAt_flipAt] using hmem
            have htwo :
                tonguesAt w (g, state) d = state ∨
                  tonguesAt w (g, state) d =
                    flipAt state FA.actionSwitch := by
              rcases hmem' with h | h | h
              · exact Or.inl h
              · exact Or.inr h
              · exact Or.inl h
            rcases htwo with h | h
            · simp [manufacturedPairActionCorners,
                ManufacturedReflector.toSupported,
                ManufacturedStayReflector.toSupported,
                ManufacturedFlipReflector.toSupported,
                LocalAction.apply, h]
            · simp [manufacturedPairActionCorners,
                ManufacturedReflector.toSupported,
                ManufacturedStayReflector.toSupported,
                ManufacturedFlipReflector.toSupported,
                LocalAction.apply, h]
          · have hcontact := contact_of_not_avoids_flip hAB
            obtain ⟨port, phase, hrun, hphase⟩ :=
              manufactured_flip_then_stay_all_time_two_phase
                FA SB state hA hB hcontact d
            have ht : tonguesAt w (g, state) d = phase := by
              simp [tonguesAt, hrun]
            rw [ht]
            rcases hphase with rfl | rfl <;>
              simp [manufacturedPairActionCorners,
                ManufacturedReflector.toSupported,
                ManufacturedStayReflector.toSupported,
                ManufacturedFlipReflector.toSupported,
                LocalAction.apply, flipAt_flipAt]
      | flip FB =>
          change PathGrooves [FA.runway, FA.candy] state at hA
          change PathGrooves [FB.runway, FB.candy] state at hB
          obtain ⟨port, phase, hrun, hmem⟩ :=
            manufactured_flip_pair_all_time_four_phase
              FA FB state hA hB d
          have ht : tonguesAt w (g, state) d = phase := by
            simp [tonguesAt, hrun]
          rw [ht]
          simpa [manufacturedPairActionCorners,
            ManufacturedReflector.toSupported,
            ManufacturedFlipReflector.toSupported,
            LocalAction.apply] using hmem

/-- Shift the action-corner law to any reached suffix configuration. -/
theorem manufactured_pair_reached_action_corners_tongues
    {w : Wiring} {g e shift d : Nat}
    (A : ManufacturedReflector w g e)
    (B : ManufacturedReflector w e g)
    (state : Tongues)
    (hA : PathGrooves A.toSupported.paths state)
    (hB : PathGrooves B.toSupported.paths state)
    {middle : Nat × Tongues}
    (hreach : stepN w shift (g, state) = some middle)
    (hlive : ∃ finish, stepN w d middle = some finish) :
    tonguesAt w middle d ∈ manufacturedPairActionCorners A B state := by
  have hmem := manufactured_pair_all_time_action_corners_tongues
    A B state hA hB (shift + d)
  have hshift := tonguesAt_add_of_reaches hreach hlive
  rw [hshift] at hmem
  exact hmem

end GeneralN
