import RunwaySpliceNovelty

/-!
# Explicit action corners for every manufactured reflector pair

The flat four-vector theorem is strengthened pointwise: at every time the
pair trajectory lies in the four algebraic corners generated by the two local
actions. At a boundary, both supports are grooved at a reference corner and
the current state differs by at most the previous action. The same progress
argument handles ordinary traversals, captures, and repaired traversals.
-/

namespace GeneralN

/-- At either boundary, an undisturbed state or one action away from it
progresses by a normal traversal, a capture, or a repaired traversal. -/
theorem ManufacturedReflector.pair_progress
    {w : Wiring} {g e : Nat}
    (A : ManufacturedReflector w g e) (B : ManufacturedReflector w e g)
    (safe : Tongues → Prop) (boundary : Nat × Tongues → Prop)
    (hsafeA : ∀ u, safe u → safe (A.toSupported.action.apply u))
    (hsafeB : ∀ u, safe u → safe (B.toSupported.action.apply u))
    (hboundary : ∀ u, safe u → PathGrooves A.toSupported.paths u →
      PathGrooves B.toSupported.paths u →
      boundary (g, u) ∧ boundary (e, A.toSupported.action.apply u))
    {u v : Tongues} (hu : safe u)
    (hA : PathGrooves A.toSupported.paths u)
    (hB : PathGrooves B.toSupported.paths u)
    (hv : v = u ∨ v = B.toSupported.action.apply u) :
    ∃ travel finish, 0 < travel ∧ stepN w travel (g, v) = some finish ∧
      boundary finish ∧ ∀ d, d ≤ travel → ∃ port phase,
        stepN w d (g, v) = some (port, phase) ∧ safe phase := by
  have hvSafe := hv.elim (fun h => h.symm ▸ hu) (fun h => h.symm ▸ hsafeB u hu)
  by_cases hAv : PathGrooves A.toSupported.paths v
  · have hBv : PathGrooves B.toSupported.paths v := by
      rcases hv with rfl | rfl
      · exact hB
      · exact hB.after_avoiding_action B.action_avoids_own_support
    refine ⟨A.toSupported.travel, (e, A.toSupported.action.apply v), A.travel_pos,
      (A.toSupported.run v hAv).1, (hboundary v hvSafe hAv hBv).2, ?_⟩
    intro d hd
    obtain ⟨port, phase, hr, hp⟩ := A.travel_two_phase_stepN v hAv hd
    exact ⟨port, phase, hr,
      hp.elim (fun h => h.symm ▸ hvSafe) (fun h => h.symm ▸ hsafeA v hvSafe)⟩
  · rcases hv with rfl | rfl
    · exact (hAv hA).elim
    · cases B with
      | stay R => exact (hAv hA).elim
      | flip R =>
          have hcontact := contact_of_not_avoids_flip
            (fun h => hAv (hA.after_avoiding_action h))
          have htrace := A.orientedRoute_trace u hA
          have hgrooved := htrace.grooved_of_switchSimple (A.orientedRoute_simple u)
          obtain ⟨path, hp, old, ho, hsw⟩ := hcontact
          obtain ⟨passage, hmem, horient⟩ := A.support_passage_on_orientedRoute u hp ho
          have hswitch : passageSwitch passage = R.actionSwitch := by
            rcases horient with rfl | rfl
            · exact hsw
            · have hs := arrive_exit_switch u old.2
              rw [hA path hp old ho] at hs
              exact hs.symm.trans hsw
          rcases R.grooved_route_fault u hB htrace hgrooved ⟨passage, hmem, hswitch⟩
              with ⟨travel, hr, hcover⟩ | ⟨cutoff, hcutoff, hpre, hmerge⟩
          · have hpos : 0 < travel := Nat.pos_of_ne_zero (by
              intro hz; subst travel
              exact hAv (show PathGrooves _ (flipAt u R.actionSwitch) from
                by simpa only [(Prod.mk.inj (Option.some.inj hr)).2] using hA))
            refine ⟨travel, (g, u), hpos, hr,
              (hboundary u hu hA hB).1, ?_⟩
            intro d hd
            obtain ⟨port, phase, hr, hp⟩ := hcover d hd
            exact ⟨port, phase, hr,
              hp.elim (fun h => h.symm ▸ hvSafe) (fun h => h.symm ▸ hu)⟩
          · have hle : cutoff ≤ A.toSupported.travel := by
              rw [A.travel_eq_oriented_add u]; omega
            refine ⟨A.toSupported.travel, (e, A.toSupported.action.apply u), A.travel_pos,
              (hmerge _ hle).trans (A.toSupported.run u hA).1,
              (hboundary u hu hA hB).2, ?_⟩
            intro d hd
            by_cases hearly : d < cutoff
            · obtain ⟨port, hr⟩ := hpre d hearly
              exact ⟨port, _, hr, hvSafe⟩
            · obtain ⟨port, phase, hr, hp⟩ := A.travel_two_phase_stepN u hA hd
              exact ⟨port, phase, (hmerge d (by omega)).trans hr,
                hp.elim (fun h => h.symm ▸ hu) (fun h => h.symm ▸ hsafeA u hu)⟩

/-- The four algebraic action corners of an opposite manufactured pair. -/
def manufacturedPairActionCorners
    {w : Wiring} {g e : Nat}
    (A : ManufacturedReflector w g e)
    (B : ManufacturedReflector w e g)
    (state : Tongues) : List Tongues :=
  [state,
   A.toSupported.action.apply state,
   B.toSupported.action.apply state,
   B.toSupported.action.apply (A.toSupported.action.apply state)]

/-- **Pointwise action-corner law for every opposite manufactured pair.** -/
theorem manufactured_pair_all_time_action_corners_tongues
    {w : Wiring} {g e : Nat}
    (A : ManufacturedReflector w g e)
    (B : ManufacturedReflector w e g)
    (state : Tongues)
    (hA : PathGrooves A.toSupported.paths state)
    (hB : PathGrooves B.toSupported.paths state)
    (d : Nat) :
    tonguesAt w (g, state) d ∈
      manufacturedPairActionCorners A B state := by
  let a := A.toSupported.action
  let b := B.toSupported.action
  let safe := fun u => u ∈ [state, a.apply state, b.apply state, b.apply (a.apply state)]
  have hsafeA : ∀ u, safe u → safe (a.apply u) := by
    intro u hu
    simp only [safe, List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl <;> simp [safe, a.involutive, a.commute b]
  have hsafeB : ∀ u, safe u → safe (b.apply u) := by
    intro u hu
    simp only [safe, List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl <;> simp [safe, b.involutive]
  let boundary := fun c : Nat × Tongues => ∃ u, safe u ∧
    PathGrooves A.toSupported.paths u ∧ PathGrooves B.toSupported.paths u ∧
      ((c.1 = g ∧ (c.2 = u ∨ c.2 = b.apply u)) ∨
       (c.1 = e ∧ (c.2 = u ∨ c.2 = a.apply u)))
  have hforward : ∀ u, safe u → PathGrooves A.toSupported.paths u →
      PathGrooves B.toSupported.paths u → boundary (g, u) ∧ boundary (e, a.apply u) := by
    intro u hu hAu hBu
    exact ⟨⟨u, hu, hAu, hBu, Or.inl ⟨rfl, Or.inl rfl⟩⟩,
      ⟨u, hu, hAu, hBu, Or.inr ⟨rfl, Or.inr rfl⟩⟩⟩
  have hbackward : ∀ u, safe u → PathGrooves B.toSupported.paths u →
      PathGrooves A.toSupported.paths u → boundary (e, u) ∧ boundary (g, b.apply u) := by
    intro u hu hBu hAu
    exact ⟨⟨u, hu, hAu, hBu, Or.inr ⟨rfl, Or.inl rfl⟩⟩,
      ⟨u, hu, hAu, hBu, Or.inl ⟨rfl, Or.inr rfl⟩⟩⟩
  have hprogress : ∀ start, boundary start → ∃ travel finish,
      0 < travel ∧ stepN w travel start = some finish ∧ boundary finish ∧
      ∀ t, t ≤ travel → ∃ port phase,
        stepN w t start = some (port, phase) ∧ safe phase := by
    intro ⟨p, v⟩ ⟨u, hu, hAu, hBu, hc⟩
    rcases hc with ⟨rfl, hv⟩ | ⟨rfl, hv⟩
    · exact A.pair_progress B safe boundary hsafeA hsafeB hforward hu hAu hBu hv
    · exact B.pair_progress A safe boundary hsafeB hsafeA hbackward hu hBu hAu hv
  obtain ⟨port, phase, hr, hs⟩ := stepN_covered_of_progress boundary safe hprogress
    (start := (g, state)) (hforward state (by simp [safe]) hA hB).1 d
  simpa [tonguesAt, hr, manufacturedPairActionCorners, safe, a, b] using hs

/-- Start the pair at the protected pre-return state. Traversing `B` reaches
its activated boundary, so every live continuation inherits the same four
corners without classifying a repair of `A`. -/
theorem ManufacturedReflector.preReturn_pair_corners
    {w : Wiring} {g e : Nat}
    (A : ManufacturedReflector w g e) (B : ManufacturedReflector w e g)
    (hB : PathGrooves B.toSupported.paths B.activatedState)
    (hpre : PathGrooves A.toSupported.paths B.preReturn.2)
    {d : Nat} (hlive : (stepN w d (g, B.activatedState)).isSome) :
    tonguesAt w (g, B.activatedState) d ∈
      [B.preReturn.2, B.activatedState, A.toSupported.action.apply B.preReturn.2,
       A.toSupported.action.apply B.activatedState] := by
  have hBpre : PathGrooves B.toSupported.paths B.preReturn.2 := by
    rw [B.preReturn_eq_action_activated]
    exact hB.after_avoiding_action B.action_avoids_own_support
  have hactivate : B.toSupported.action.apply B.preReturn.2 = B.activatedState := by
    rw [B.preReturn_eq_action_activated, B.toSupported.action.involutive]
  have hreach := (B.toSupported.run B.preReturn.2 hBpre).1
  rw [hactivate] at hreach
  rw [← tonguesAt_add_of_reaches hreach (Option.isSome_iff_exists.mp hlive)]
  simpa [manufacturedPairActionCorners, hactivate] using
    manufactured_pair_all_time_action_corners_tongues B A B.preReturn.2 hBpre hpre _

end GeneralN
