import TripleSelfLinkSimpleCycleTail
import CoefficientOneSeven

namespace GeneralN

#check rawTwoVectorTail_of_stable_simple_cycle_exact
#check RawCycleThroughSelfLink.close_tail_of_simple_cycle_trace_exact
#check RawSixEventReduction.tail_simple_cycle_false
#check RawSixEventReduction.tail_cycle_self_link_false
#check CertifiedEndpointEmptyABCABC.tail_self_link_endpoint_is_early

#check KnownEdgeFiveRepeatedWriterNovelty
#check knownEdgeFiveRepeatedWriterNovelty_of_sharpSixEventResidueImpossible
#check knownEdge_distinct_le_N_add_six_of_fiveRepeatedWriterNovelty
#check StateLawNAddSeven
#check stateLawNAddSeven_of_sharpSixEventResidueImpossible

end GeneralN
